#服务器参数配置
server:
  port: 8080
  address: 127.0.0.1
  context-path: /SpringbootForRedis
  session:
    timeout: 30
spring:

  #数据库信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    #连接池的配置信息
   # 下面为连接池的补充设置，应用到上面所有数据源中
     # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5

  #redis配置
  redis:
    host: 192.168.1.102
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: 1
    timeout: 0
    database: 0
    ssl: false


#mybatis配置
mybatis:
  type-aliases-package: com.orion.domain
  mapper-locations: classpath*:com/orion/mapper/*.xml
  logging:
      level:
          com.orion.dao: DEBUG


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql






